name: example
description: simple_rich_text example

version: 1.0.3

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'
  flutter: '3.12.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  simple_rich_text:
    path: ../

flutter:
  uses-material-design: true
