include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - route/**
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - lib/app/di/injectable.config.dart
    - lib/firebase_options.dart
    - lib/generated/*
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true
  strong-mode:
    implicit-casts: false
  plugins:
    - dart_code_metrics
  errors:
    invalid_annotation_target: ignore

dart_code_metrics:
  anti-patterns:
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maintainability-index: 50
    maximum-nesting: 5
    number-of-parameters: 5
    source-lines-of-code: 50
    technical-debt:
      threshold: 1
      todo-cost: 4
      ignore-cost: 8
      ignore-for-file-cost: 16
      as-dynamic-cost: 16
      deprecated-annotations-cost: 2
      file-nullsafety-migration-cost: 2
      unit-type: "hours"
  metrics-exclude:
    - test/src/analyzer_plugin/**
    - lib/route/**
    - lib/generated/**
  rules:
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-equal-then-else
    - no-object-declaration
    - prefer-conditional-expressions
    - prefer-first
    - prefer-last
    - prefer-match-file-name:
        exclude:
          - test/**

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - cancel_subscriptions
    - cascade_invocations
    - close_sinks
    - comment_references
    - depend_on_referenced_packages
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - eol_at_end_of_file
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_private_types_in_public_api
    - literal_only_boolean_expressions
    - missing_whitespace_between_adjacent_strings
    - no_default_cases
    - no_logic_in_create_state
    - no_runtimeType_toString
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_constructor_name
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unsafe_html
    - use_build_context_synchronously
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - annotate_overrides
    - avoid_single_cascade_in_expression_statements
    - await_only_futures
    - camel_case_types
    - camel_case_extensions
    - exhaustive_cases
    - file_names
    - non_constant_identifier_names
    - prefer_final_fields
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - prefer_spread_collections
    - slash_for_doc_comments
    - unnecessary_const
    - unnecessary_late
    - unnecessary_new
    - unnecessary_this
    - unnecessary_string_interpolations
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters