name: simple_rich_text
description: Display a Dart string in Flutter using simple rich text characters.
version: 2.0.50 #NOEDIT
homepage: https://github.com/remoteportal/simple_rich_text

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.13.6'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
