name: simple_rich_text
description: Display a Dart string in Flutter using simple rich text characters.
publish_to: "none"
version: 2.1.3

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed_annotation: ^2.4.1
  url_launcher: ^6.0.3

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6

flutter: null
